### ISSUE TITLE
Problema ao tentar chamar o endpoint

### ISSUE THREAD

**Issue by NewarkX** [eldermoraes/viagem-app#3]
Estou tentando criar uma reserva através do endpoint http://localhost:8081/reserva-cli/newReserva, a resposta que aparece é 405Method Not Allowed, link do repositório, https://github.com/NewarkX/viajem-app, e ao tentar chamar o servico que cria o cliente,
ele cria o cliente porém me retorna um erro gigante kk, o endpoint é este http://localhost:8081/cliente-cli/newCliente

**Comment by eldermoraes** [comment]
No "agencia-cli", ajusta o método newCliente do ClienteResource pra ficar assim:

    @GET
    @Path("newCliente")
    public Response newCliente(){
        Cliente cliente = Cliente.of(99, "Remoto");

        return clienteService.newCliente(cliente);
    }
